// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/ocm/core/v1beta1/ocm_core_api.proto

package corev1beta1

import (
	context "context"
	fmt "fmt"
	v1beta11 "github.com/cs3org/go-cs3apis/cs3/identity/user/v1beta1"
	v1beta14 "github.com/cs3org/go-cs3apis/cs3/rpc/v1beta1"
	v1beta13 "github.com/cs3org/go-cs3apis/cs3/sharing/ocm/v1beta1"
	v1beta12 "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
	v1beta1 "github.com/cs3org/go-cs3apis/cs3/types/v1beta1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// https://rawgit.com/GEANT/OCM-API/v1/docs.html#null%2Fpaths%2F~1shares%2Fpost
type CreateOCMCoreShareRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// OPTIONAL.
	// Description for the share.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// REQUIRED.
	// Name of the resource (file or folder).
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// REQUIRED.
	// Identifier to identify the resource at the provider side. This is unique per provider.
	ResourceId string `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// REQUIRED.
	// Provider specific identifier of the owner of the resource.
	Owner *v1beta11.UserId `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	// REQUIRED.
	// Provider specific identifier of the user that wants to share the resource.
	Sender *v1beta11.UserId `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	// REQUIRED.
	// Consumer specific identifier of the user or group the provider wants to share the resource with.
	// This is known in advance, for example using the OCM invitation flow.
	// Please note that the consumer service endpoint is known in advance as well, so this is no part of the request body.
	// TODO: this field needs to represent either a user or group in the future, not only a user.
	ShareWith *v1beta11.UserId `protobuf:"bytes,7,opt,name=share_with,json=shareWith,proto3" json:"share_with,omitempty"`
	// REQUIRED.
	// Resource type.
	ResourceType v1beta12.ResourceType `protobuf:"varint,8,opt,name=resource_type,json=resourceType,proto3,enum=cs3.storage.provider.v1beta1.ResourceType" json:"resource_type,omitempty"`
	// REQUIRED.
	// Recipient share type.
	ShareType v1beta13.ShareType `protobuf:"varint,9,opt,name=share_type,json=shareType,proto3,enum=cs3.sharing.ocm.v1beta1.ShareType" json:"share_type,omitempty"`
	// OPTIONAL.
	// The expiration time for the ocm share.
	Expiration *v1beta1.Timestamp `protobuf:"bytes,10,opt,name=expiration,proto3" json:"expiration,omitempty"`
	// REQUIRED.
	// The protocols which are used to establish synchronisation.
	Protocols            []*v1beta13.Protocol `protobuf:"bytes,11,rep,name=protocols,proto3" json:"protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateOCMCoreShareRequest) Reset()         { *m = CreateOCMCoreShareRequest{} }
func (m *CreateOCMCoreShareRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOCMCoreShareRequest) ProtoMessage()    {}
func (*CreateOCMCoreShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e8f411283db0fc7, []int{0}
}

func (m *CreateOCMCoreShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOCMCoreShareRequest.Unmarshal(m, b)
}
func (m *CreateOCMCoreShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOCMCoreShareRequest.Marshal(b, m, deterministic)
}
func (m *CreateOCMCoreShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOCMCoreShareRequest.Merge(m, src)
}
func (m *CreateOCMCoreShareRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOCMCoreShareRequest.Size(m)
}
func (m *CreateOCMCoreShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOCMCoreShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOCMCoreShareRequest proto.InternalMessageInfo

func (m *CreateOCMCoreShareRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreateOCMCoreShareRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateOCMCoreShareRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOCMCoreShareRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *CreateOCMCoreShareRequest) GetOwner() *v1beta11.UserId {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CreateOCMCoreShareRequest) GetSender() *v1beta11.UserId {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *CreateOCMCoreShareRequest) GetShareWith() *v1beta11.UserId {
	if m != nil {
		return m.ShareWith
	}
	return nil
}

func (m *CreateOCMCoreShareRequest) GetResourceType() v1beta12.ResourceType {
	if m != nil {
		return m.ResourceType
	}
	return v1beta12.ResourceType_RESOURCE_TYPE_INVALID
}

func (m *CreateOCMCoreShareRequest) GetShareType() v1beta13.ShareType {
	if m != nil {
		return m.ShareType
	}
	return v1beta13.ShareType_SHARE_TYPE_INVALID
}

func (m *CreateOCMCoreShareRequest) GetExpiration() *v1beta1.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *CreateOCMCoreShareRequest) GetProtocols() []*v1beta13.Protocol {
	if m != nil {
		return m.Protocols
	}
	return nil
}

type CreateOCMCoreShareResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta14.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// Unique ID to identify the share at the consumer side.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// REQUIRED.
	Created              *v1beta1.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateOCMCoreShareResponse) Reset()         { *m = CreateOCMCoreShareResponse{} }
func (m *CreateOCMCoreShareResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOCMCoreShareResponse) ProtoMessage()    {}
func (*CreateOCMCoreShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e8f411283db0fc7, []int{1}
}

func (m *CreateOCMCoreShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOCMCoreShareResponse.Unmarshal(m, b)
}
func (m *CreateOCMCoreShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOCMCoreShareResponse.Marshal(b, m, deterministic)
}
func (m *CreateOCMCoreShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOCMCoreShareResponse.Merge(m, src)
}
func (m *CreateOCMCoreShareResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOCMCoreShareResponse.Size(m)
}
func (m *CreateOCMCoreShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOCMCoreShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOCMCoreShareResponse proto.InternalMessageInfo

func (m *CreateOCMCoreShareResponse) GetStatus() *v1beta14.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateOCMCoreShareResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreateOCMCoreShareResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOCMCoreShareResponse) GetCreated() *v1beta1.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateOCMCoreShareRequest)(nil), "cs3.ocm.core.v1beta1.CreateOCMCoreShareRequest")
	proto.RegisterType((*CreateOCMCoreShareResponse)(nil), "cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse")
}

func init() {
	proto.RegisterFile("cs3/ocm/core/v1beta1/ocm_core_api.proto", fileDescriptor_4e8f411283db0fc7)
}

var fileDescriptor_4e8f411283db0fc7 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6a, 0x13, 0x4f,
	0x14, 0x67, 0xb7, 0x6d, 0xfa, 0xcf, 0xe4, 0x6f, 0x85, 0xa1, 0xe0, 0x36, 0x54, 0x8c, 0xbd, 0xb1,
	0x8a, 0xcc, 0x9a, 0x06, 0x14, 0x41, 0xd0, 0x76, 0xaf, 0x7a, 0x21, 0x5b, 0xd6, 0xaa, 0x20, 0x81,
	0xb0, 0x9d, 0x3d, 0x34, 0x03, 0xee, 0xce, 0x74, 0x66, 0xd2, 0x98, 0x07, 0xf0, 0x45, 0xbc, 0xf4,
	0x49, 0xc4, 0x87, 0xf1, 0x19, 0x64, 0xce, 0xce, 0x6e, 0x03, 0xa6, 0x9a, 0xbb, 0xee, 0xf9, 0x7d,
	0xcc, 0xf9, 0xf8, 0x35, 0xe4, 0x11, 0x37, 0xa3, 0x58, 0xf2, 0x32, 0xe6, 0x52, 0x43, 0x7c, 0x3d,
	0xbc, 0x00, 0x9b, 0x0f, 0x5d, 0x61, 0xe2, 0x0a, 0x93, 0x5c, 0x09, 0xa6, 0xb4, 0xb4, 0x92, 0xee,
	0x72, 0x33, 0x62, 0x92, 0x97, 0xcc, 0xd5, 0x99, 0x27, 0xf6, 0x1f, 0x3b, 0xb9, 0x28, 0xa0, 0xb2,
	0xc2, 0x2e, 0xe2, 0x99, 0x01, 0xdd, 0x7a, 0x68, 0x30, 0x72, 0xa6, 0x39, 0x98, 0xda, 0xa0, 0xff,
	0xd4, 0x51, 0x8d, 0x95, 0x3a, 0xbf, 0x84, 0x58, 0x69, 0x79, 0x2d, 0x8a, 0xbf, 0xb0, 0xf7, 0x1d,
	0x5b, 0x2b, 0xde, 0x12, 0x8c, 0xcd, 0xed, 0xac, 0x41, 0xef, 0x3b, 0xd4, 0x2e, 0x14, 0x98, 0x16,
	0xc7, 0x2f, 0x0f, 0xe3, 0x50, 0x66, 0x9a, 0x6b, 0x51, 0x5d, 0xe2, 0x70, 0xb7, 0xbc, 0x72, 0xf0,
	0x6b, 0x93, 0xec, 0x25, 0x1a, 0x72, 0x0b, 0x69, 0xf2, 0x36, 0x91, 0x1a, 0xde, 0x4d, 0x73, 0x0d,
	0x19, 0x5c, 0xcd, 0xc0, 0x58, 0x3a, 0x24, 0x1d, 0xa9, 0xf2, 0xab, 0x19, 0x44, 0xc1, 0x20, 0x38,
	0xec, 0x1d, 0xed, 0x31, 0xb7, 0x83, 0xfa, 0x21, 0xef, 0xc8, 0x52, 0x24, 0x64, 0x9e, 0x48, 0x07,
	0xa4, 0x57, 0x80, 0xe1, 0x5a, 0x28, 0x2b, 0x64, 0x15, 0x85, 0x83, 0xe0, 0xb0, 0x9b, 0x2d, 0x97,
	0x28, 0x25, 0x9b, 0x55, 0x5e, 0x42, 0xb4, 0x81, 0x10, 0xfe, 0x4d, 0x1f, 0x90, 0x5e, 0xd3, 0xd9,
	0x44, 0x14, 0xd1, 0x26, 0x42, 0xa4, 0x29, 0x9d, 0x16, 0xf4, 0x05, 0xd9, 0x92, 0xf3, 0x0a, 0x74,
	0xb4, 0x85, 0x8d, 0x3c, 0xc4, 0x46, 0x9a, 0xb5, 0x33, 0xb7, 0xf6, 0xb6, 0xa1, 0xf7, 0x06, 0xf4,
	0x69, 0x91, 0xd5, 0x7c, 0xfa, 0x92, 0x74, 0x0c, 0x54, 0x05, 0xe8, 0xa8, 0xb3, 0xae, 0xd2, 0x0b,
	0xe8, 0x1b, 0x42, 0xdc, 0x0a, 0x61, 0x32, 0x17, 0x76, 0x1a, 0x6d, 0xaf, 0x2b, 0xef, 0xa2, 0xe8,
	0xa3, 0xb0, 0x53, 0x9a, 0x92, 0x3b, 0xed, 0x58, 0x6e, 0x6b, 0xd1, 0x7f, 0x83, 0xe0, 0x70, 0xe7,
	0xe8, 0x09, 0x9a, 0xf8, 0x24, 0xb0, 0x26, 0x09, 0xad, 0x4f, 0xe6, 0x25, 0xe7, 0x0b, 0x05, 0xd9,
	0xff, 0x7a, 0xe9, 0x8b, 0x1e, 0x37, 0x2d, 0xa1, 0x5b, 0x17, 0xdd, 0x0e, 0x6a, 0xb7, 0xfa, 0xd8,
	0x18, 0xd0, 0xc6, 0x08, 0x6f, 0x89, 0x2e, 0x75, 0x4f, 0x68, 0xf1, 0x8a, 0x10, 0xf8, 0xa2, 0x84,
	0xce, 0xf1, 0x3e, 0x04, 0xa7, 0xda, 0x5f, 0x71, 0xd7, 0x73, 0x51, 0x82, 0xb1, 0x79, 0xa9, 0xb2,
	0x25, 0x3e, 0x7d, 0x4d, 0xba, 0x18, 0x1c, 0x2e, 0x3f, 0x9b, 0xa8, 0x37, 0xd8, 0x68, 0x57, 0xb2,
	0xea, 0xfd, 0x33, 0xcf, 0xcc, 0x6e, 0x34, 0x07, 0x3f, 0x02, 0xd2, 0x5f, 0x15, 0x38, 0xa3, 0x64,
	0x65, 0x80, 0xc6, 0xa4, 0x53, 0xe7, 0xdc, 0x27, 0xee, 0x1e, 0x9a, 0x6b, 0xc5, 0x6f, 0x86, 0x42,
	0x38, 0xf3, 0xb4, 0xa5, 0x88, 0x86, 0xeb, 0x46, 0x74, 0x87, 0x84, 0xa2, 0xf0, 0xf1, 0x0b, 0x45,
	0x41, 0x9f, 0x93, 0x6d, 0x8e, 0x1d, 0xd5, 0xc1, 0xfb, 0xd7, 0x3a, 0x1a, 0xf2, 0xd1, 0xd7, 0x80,
	0x90, 0x94, 0x97, 0x6e, 0x88, 0xe3, 0xb3, 0x53, 0x3a, 0x27, 0xf4, 0xcf, 0xc1, 0x68, 0xcc, 0x56,
	0xfd, 0x6c, 0xb0, 0x5b, 0xff, 0xe7, 0xfa, 0xcf, 0xd6, 0x17, 0xd4, 0x3b, 0x3b, 0xa9, 0x48, 0xc4,
	0x65, 0xb9, 0x52, 0x76, 0x72, 0xb7, 0x69, 0x50, 0x09, 0xbc, 0xc6, 0x59, 0xf0, 0xa9, 0xe7, 0x08,
	0x1e, 0xff, 0x16, 0x6e, 0x24, 0x69, 0xf2, 0x3d, 0xdc, 0x4d, 0xcc, 0x88, 0xa5, 0xbc, 0x64, 0x8e,
	0xcb, 0x3e, 0x0c, 0x4f, 0x1c, 0xf8, 0x13, 0xcb, 0xe3, 0x94, 0x97, 0x63, 0x57, 0x1e, 0xfb, 0xf2,
	0x45, 0x07, 0xaf, 0x39, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xab, 0xa5, 0x11, 0x37, 0x3a, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OcmCoreAPIClient is the client API for OcmCoreAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OcmCoreAPIClient interface {
	// Creates a new ocm share.
	CreateOCMCoreShare(ctx context.Context, in *CreateOCMCoreShareRequest, opts ...grpc.CallOption) (*CreateOCMCoreShareResponse, error)
}

type ocmCoreAPIClient struct {
	cc *grpc.ClientConn
}

func NewOcmCoreAPIClient(cc *grpc.ClientConn) OcmCoreAPIClient {
	return &ocmCoreAPIClient{cc}
}

func (c *ocmCoreAPIClient) CreateOCMCoreShare(ctx context.Context, in *CreateOCMCoreShareRequest, opts ...grpc.CallOption) (*CreateOCMCoreShareResponse, error) {
	out := new(CreateOCMCoreShareResponse)
	err := c.cc.Invoke(ctx, "/cs3.ocm.core.v1beta1.OcmCoreAPI/CreateOCMCoreShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OcmCoreAPIServer is the server API for OcmCoreAPI service.
type OcmCoreAPIServer interface {
	// Creates a new ocm share.
	CreateOCMCoreShare(context.Context, *CreateOCMCoreShareRequest) (*CreateOCMCoreShareResponse, error)
}

// UnimplementedOcmCoreAPIServer can be embedded to have forward compatible implementations.
type UnimplementedOcmCoreAPIServer struct {
}

func (*UnimplementedOcmCoreAPIServer) CreateOCMCoreShare(ctx context.Context, req *CreateOCMCoreShareRequest) (*CreateOCMCoreShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOCMCoreShare not implemented")
}

func RegisterOcmCoreAPIServer(s *grpc.Server, srv OcmCoreAPIServer) {
	s.RegisterService(&_OcmCoreAPI_serviceDesc, srv)
}

func _OcmCoreAPI_CreateOCMCoreShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOCMCoreShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OcmCoreAPIServer).CreateOCMCoreShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.ocm.core.v1beta1.OcmCoreAPI/CreateOCMCoreShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OcmCoreAPIServer).CreateOCMCoreShare(ctx, req.(*CreateOCMCoreShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OcmCoreAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cs3.ocm.core.v1beta1.OcmCoreAPI",
	HandlerType: (*OcmCoreAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOCMCoreShare",
			Handler:    _OcmCoreAPI_CreateOCMCoreShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cs3/ocm/core/v1beta1/ocm_core_api.proto",
}
