// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/storage/provider/v1beta1/spaces_api.proto

package providerv1beta1

import (
	context "context"
	fmt "fmt"
	v1beta11 "github.com/cs3org/go-cs3apis/cs3/identity/user/v1beta1"
	v1beta12 "github.com/cs3org/go-cs3apis/cs3/rpc/v1beta1"
	v1beta1 "github.com/cs3org/go-cs3apis/cs3/types/v1beta1"
	proto "github.com/golang/protobuf/proto"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The filter to apply.
type ListStorageSpacesRequest_Filter_Type int32

const (
	ListStorageSpacesRequest_Filter_TYPE_INVALID    ListStorageSpacesRequest_Filter_Type = 0
	ListStorageSpacesRequest_Filter_TYPE_NO         ListStorageSpacesRequest_Filter_Type = 1
	ListStorageSpacesRequest_Filter_TYPE_ID         ListStorageSpacesRequest_Filter_Type = 2
	ListStorageSpacesRequest_Filter_TYPE_OWNER      ListStorageSpacesRequest_Filter_Type = 3
	ListStorageSpacesRequest_Filter_TYPE_SPACE_TYPE ListStorageSpacesRequest_Filter_Type = 4
	ListStorageSpacesRequest_Filter_TYPE_PATH       ListStorageSpacesRequest_Filter_Type = 5
	ListStorageSpacesRequest_Filter_TYPE_USER       ListStorageSpacesRequest_Filter_Type = 6
)

var ListStorageSpacesRequest_Filter_Type_name = map[int32]string{
	0: "TYPE_INVALID",
	1: "TYPE_NO",
	2: "TYPE_ID",
	3: "TYPE_OWNER",
	4: "TYPE_SPACE_TYPE",
	5: "TYPE_PATH",
	6: "TYPE_USER",
}

var ListStorageSpacesRequest_Filter_Type_value = map[string]int32{
	"TYPE_INVALID":    0,
	"TYPE_NO":         1,
	"TYPE_ID":         2,
	"TYPE_OWNER":      3,
	"TYPE_SPACE_TYPE": 4,
	"TYPE_PATH":       5,
	"TYPE_USER":       6,
}

func (x ListStorageSpacesRequest_Filter_Type) String() string {
	return proto.EnumName(ListStorageSpacesRequest_Filter_Type_name, int32(x))
}

func (ListStorageSpacesRequest_Filter_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{2, 0, 0}
}

type CreateStorageSpaceRequest struct {
	// OPTIONAL.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	Owner *v1beta11.User `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// OPTIONAL.
	// Could be 'home', 'share', 'project', 'space'...
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// OPTIONAL.
	// User readable name of the storage space.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// OPTIONAL.
	Quota                *Quota   `protobuf:"bytes,5,opt,name=quota,proto3" json:"quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStorageSpaceRequest) Reset()         { *m = CreateStorageSpaceRequest{} }
func (m *CreateStorageSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStorageSpaceRequest) ProtoMessage()    {}
func (*CreateStorageSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{0}
}

func (m *CreateStorageSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorageSpaceRequest.Unmarshal(m, b)
}
func (m *CreateStorageSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorageSpaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateStorageSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorageSpaceRequest.Merge(m, src)
}
func (m *CreateStorageSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStorageSpaceRequest.Size(m)
}
func (m *CreateStorageSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorageSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorageSpaceRequest proto.InternalMessageInfo

func (m *CreateStorageSpaceRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreateStorageSpaceRequest) GetOwner() *v1beta11.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CreateStorageSpaceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateStorageSpaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStorageSpaceRequest) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

type CreateStorageSpaceResponse struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// REQUIRED.
	// The created storage space.
	StorageSpace         *StorageSpace `protobuf:"bytes,3,opt,name=storage_space,json=storageSpace,proto3" json:"storage_space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateStorageSpaceResponse) Reset()         { *m = CreateStorageSpaceResponse{} }
func (m *CreateStorageSpaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStorageSpaceResponse) ProtoMessage()    {}
func (*CreateStorageSpaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{1}
}

func (m *CreateStorageSpaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorageSpaceResponse.Unmarshal(m, b)
}
func (m *CreateStorageSpaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorageSpaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateStorageSpaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorageSpaceResponse.Merge(m, src)
}
func (m *CreateStorageSpaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStorageSpaceResponse.Size(m)
}
func (m *CreateStorageSpaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorageSpaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorageSpaceResponse proto.InternalMessageInfo

func (m *CreateStorageSpaceResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *CreateStorageSpaceResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateStorageSpaceResponse) GetStorageSpace() *StorageSpace {
	if m != nil {
		return m.StorageSpace
	}
	return nil
}

type ListStorageSpacesRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// OPTIONAL.
	// The list of filters to apply if any.
	Filters []*ListStorageSpacesRequest_Filter `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	// OPTIONAL.
	// The field mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	FieldMask *field_mask.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// OPTIONAL.
	// Clients use this field to specify the maximum number of results to be returned by the server.
	// The server may further constrain the maximum number of results returned in a single page.
	// If the page_size is 0, the server will decide the number of results to be returned.
	// see https://cloud.google.com/apis/design/design_patterns#list_pagination
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// OPTIONAL.
	// The client uses this field to request a specific page of the list results.
	PageToken            string   `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStorageSpacesRequest) Reset()         { *m = ListStorageSpacesRequest{} }
func (m *ListStorageSpacesRequest) String() string { return proto.CompactTextString(m) }
func (*ListStorageSpacesRequest) ProtoMessage()    {}
func (*ListStorageSpacesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{2}
}

func (m *ListStorageSpacesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStorageSpacesRequest.Unmarshal(m, b)
}
func (m *ListStorageSpacesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStorageSpacesRequest.Marshal(b, m, deterministic)
}
func (m *ListStorageSpacesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStorageSpacesRequest.Merge(m, src)
}
func (m *ListStorageSpacesRequest) XXX_Size() int {
	return xxx_messageInfo_ListStorageSpacesRequest.Size(m)
}
func (m *ListStorageSpacesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStorageSpacesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStorageSpacesRequest proto.InternalMessageInfo

func (m *ListStorageSpacesRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ListStorageSpacesRequest) GetFilters() []*ListStorageSpacesRequest_Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ListStorageSpacesRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListStorageSpacesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListStorageSpacesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// Represents a filter to apply to the request.
type ListStorageSpacesRequest_Filter struct {
	// REQUIRED.
	Type ListStorageSpacesRequest_Filter_Type `protobuf:"varint,1,opt,name=type,proto3,enum=cs3.storage.provider.v1beta1.ListStorageSpacesRequest_Filter_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Term:
	//	*ListStorageSpacesRequest_Filter_Id
	//	*ListStorageSpacesRequest_Filter_Owner
	//	*ListStorageSpacesRequest_Filter_SpaceType
	//	*ListStorageSpacesRequest_Filter_Path
	//	*ListStorageSpacesRequest_Filter_User
	Term                 isListStorageSpacesRequest_Filter_Term `protobuf_oneof:"term"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ListStorageSpacesRequest_Filter) Reset()         { *m = ListStorageSpacesRequest_Filter{} }
func (m *ListStorageSpacesRequest_Filter) String() string { return proto.CompactTextString(m) }
func (*ListStorageSpacesRequest_Filter) ProtoMessage()    {}
func (*ListStorageSpacesRequest_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{2, 0}
}

func (m *ListStorageSpacesRequest_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStorageSpacesRequest_Filter.Unmarshal(m, b)
}
func (m *ListStorageSpacesRequest_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStorageSpacesRequest_Filter.Marshal(b, m, deterministic)
}
func (m *ListStorageSpacesRequest_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStorageSpacesRequest_Filter.Merge(m, src)
}
func (m *ListStorageSpacesRequest_Filter) XXX_Size() int {
	return xxx_messageInfo_ListStorageSpacesRequest_Filter.Size(m)
}
func (m *ListStorageSpacesRequest_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStorageSpacesRequest_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListStorageSpacesRequest_Filter proto.InternalMessageInfo

func (m *ListStorageSpacesRequest_Filter) GetType() ListStorageSpacesRequest_Filter_Type {
	if m != nil {
		return m.Type
	}
	return ListStorageSpacesRequest_Filter_TYPE_INVALID
}

type isListStorageSpacesRequest_Filter_Term interface {
	isListStorageSpacesRequest_Filter_Term()
}

type ListStorageSpacesRequest_Filter_Id struct {
	Id *StorageSpaceId `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type ListStorageSpacesRequest_Filter_Owner struct {
	Owner *v1beta11.UserId `protobuf:"bytes,3,opt,name=owner,proto3,oneof"`
}

type ListStorageSpacesRequest_Filter_SpaceType struct {
	SpaceType string `protobuf:"bytes,4,opt,name=space_type,json=spaceType,proto3,oneof"`
}

type ListStorageSpacesRequest_Filter_Path struct {
	Path string `protobuf:"bytes,5,opt,name=path,proto3,oneof"`
}

type ListStorageSpacesRequest_Filter_User struct {
	User *v1beta11.UserId `protobuf:"bytes,6,opt,name=user,proto3,oneof"`
}

func (*ListStorageSpacesRequest_Filter_Id) isListStorageSpacesRequest_Filter_Term() {}

func (*ListStorageSpacesRequest_Filter_Owner) isListStorageSpacesRequest_Filter_Term() {}

func (*ListStorageSpacesRequest_Filter_SpaceType) isListStorageSpacesRequest_Filter_Term() {}

func (*ListStorageSpacesRequest_Filter_Path) isListStorageSpacesRequest_Filter_Term() {}

func (*ListStorageSpacesRequest_Filter_User) isListStorageSpacesRequest_Filter_Term() {}

func (m *ListStorageSpacesRequest_Filter) GetTerm() isListStorageSpacesRequest_Filter_Term {
	if m != nil {
		return m.Term
	}
	return nil
}

func (m *ListStorageSpacesRequest_Filter) GetId() *StorageSpaceId {
	if x, ok := m.GetTerm().(*ListStorageSpacesRequest_Filter_Id); ok {
		return x.Id
	}
	return nil
}

func (m *ListStorageSpacesRequest_Filter) GetOwner() *v1beta11.UserId {
	if x, ok := m.GetTerm().(*ListStorageSpacesRequest_Filter_Owner); ok {
		return x.Owner
	}
	return nil
}

func (m *ListStorageSpacesRequest_Filter) GetSpaceType() string {
	if x, ok := m.GetTerm().(*ListStorageSpacesRequest_Filter_SpaceType); ok {
		return x.SpaceType
	}
	return ""
}

func (m *ListStorageSpacesRequest_Filter) GetPath() string {
	if x, ok := m.GetTerm().(*ListStorageSpacesRequest_Filter_Path); ok {
		return x.Path
	}
	return ""
}

func (m *ListStorageSpacesRequest_Filter) GetUser() *v1beta11.UserId {
	if x, ok := m.GetTerm().(*ListStorageSpacesRequest_Filter_User); ok {
		return x.User
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListStorageSpacesRequest_Filter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListStorageSpacesRequest_Filter_Id)(nil),
		(*ListStorageSpacesRequest_Filter_Owner)(nil),
		(*ListStorageSpacesRequest_Filter_SpaceType)(nil),
		(*ListStorageSpacesRequest_Filter_Path)(nil),
		(*ListStorageSpacesRequest_Filter_User)(nil),
	}
}

type ListStorageSpacesResponse struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// REQUIRED.
	StorageSpaces []*StorageSpace `protobuf:"bytes,3,rep,name=storage_spaces,json=storageSpaces,proto3" json:"storage_spaces,omitempty"`
	// OPTIONAL.
	// This field represents the pagination token to retrieve the next page of results.
	// If the value is "", it means no further results for the request.
	// see https://cloud.google.com/apis/design/design_patterns#list_pagination
	NextPageToken        string   `protobuf:"bytes,4,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStorageSpacesResponse) Reset()         { *m = ListStorageSpacesResponse{} }
func (m *ListStorageSpacesResponse) String() string { return proto.CompactTextString(m) }
func (*ListStorageSpacesResponse) ProtoMessage()    {}
func (*ListStorageSpacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{3}
}

func (m *ListStorageSpacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStorageSpacesResponse.Unmarshal(m, b)
}
func (m *ListStorageSpacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStorageSpacesResponse.Marshal(b, m, deterministic)
}
func (m *ListStorageSpacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStorageSpacesResponse.Merge(m, src)
}
func (m *ListStorageSpacesResponse) XXX_Size() int {
	return xxx_messageInfo_ListStorageSpacesResponse.Size(m)
}
func (m *ListStorageSpacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStorageSpacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStorageSpacesResponse proto.InternalMessageInfo

func (m *ListStorageSpacesResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ListStorageSpacesResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListStorageSpacesResponse) GetStorageSpaces() []*StorageSpace {
	if m != nil {
		return m.StorageSpaces
	}
	return nil
}

func (m *ListStorageSpacesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type UpdateStorageSpaceRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	StorageSpace         *StorageSpace `protobuf:"bytes,2,opt,name=storage_space,json=storageSpace,proto3" json:"storage_space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateStorageSpaceRequest) Reset()         { *m = UpdateStorageSpaceRequest{} }
func (m *UpdateStorageSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStorageSpaceRequest) ProtoMessage()    {}
func (*UpdateStorageSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{4}
}

func (m *UpdateStorageSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStorageSpaceRequest.Unmarshal(m, b)
}
func (m *UpdateStorageSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStorageSpaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStorageSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStorageSpaceRequest.Merge(m, src)
}
func (m *UpdateStorageSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStorageSpaceRequest.Size(m)
}
func (m *UpdateStorageSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStorageSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStorageSpaceRequest proto.InternalMessageInfo

func (m *UpdateStorageSpaceRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *UpdateStorageSpaceRequest) GetStorageSpace() *StorageSpace {
	if m != nil {
		return m.StorageSpace
	}
	return nil
}

type UpdateStorageSpaceResponse struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// REQUIRED.
	// The updated storage space.
	StorageSpace         *StorageSpace `protobuf:"bytes,3,opt,name=storage_space,json=storageSpace,proto3" json:"storage_space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateStorageSpaceResponse) Reset()         { *m = UpdateStorageSpaceResponse{} }
func (m *UpdateStorageSpaceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStorageSpaceResponse) ProtoMessage()    {}
func (*UpdateStorageSpaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{5}
}

func (m *UpdateStorageSpaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStorageSpaceResponse.Unmarshal(m, b)
}
func (m *UpdateStorageSpaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStorageSpaceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateStorageSpaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStorageSpaceResponse.Merge(m, src)
}
func (m *UpdateStorageSpaceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStorageSpaceResponse.Size(m)
}
func (m *UpdateStorageSpaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStorageSpaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStorageSpaceResponse proto.InternalMessageInfo

func (m *UpdateStorageSpaceResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *UpdateStorageSpaceResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdateStorageSpaceResponse) GetStorageSpace() *StorageSpace {
	if m != nil {
		return m.StorageSpace
	}
	return nil
}

type DeleteStorageSpaceRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	Id                   *StorageSpaceId `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeleteStorageSpaceRequest) Reset()         { *m = DeleteStorageSpaceRequest{} }
func (m *DeleteStorageSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStorageSpaceRequest) ProtoMessage()    {}
func (*DeleteStorageSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{6}
}

func (m *DeleteStorageSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorageSpaceRequest.Unmarshal(m, b)
}
func (m *DeleteStorageSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorageSpaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorageSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorageSpaceRequest.Merge(m, src)
}
func (m *DeleteStorageSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorageSpaceRequest.Size(m)
}
func (m *DeleteStorageSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorageSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorageSpaceRequest proto.InternalMessageInfo

func (m *DeleteStorageSpaceRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *DeleteStorageSpaceRequest) GetId() *StorageSpaceId {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteStorageSpaceResponse struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The response status.
	Status               *v1beta12.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteStorageSpaceResponse) Reset()         { *m = DeleteStorageSpaceResponse{} }
func (m *DeleteStorageSpaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStorageSpaceResponse) ProtoMessage()    {}
func (*DeleteStorageSpaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a299dd75d83fb33e, []int{7}
}

func (m *DeleteStorageSpaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorageSpaceResponse.Unmarshal(m, b)
}
func (m *DeleteStorageSpaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorageSpaceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStorageSpaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorageSpaceResponse.Merge(m, src)
}
func (m *DeleteStorageSpaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStorageSpaceResponse.Size(m)
}
func (m *DeleteStorageSpaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorageSpaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorageSpaceResponse proto.InternalMessageInfo

func (m *DeleteStorageSpaceResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *DeleteStorageSpaceResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("cs3.storage.provider.v1beta1.ListStorageSpacesRequest_Filter_Type", ListStorageSpacesRequest_Filter_Type_name, ListStorageSpacesRequest_Filter_Type_value)
	proto.RegisterType((*CreateStorageSpaceRequest)(nil), "cs3.storage.provider.v1beta1.CreateStorageSpaceRequest")
	proto.RegisterType((*CreateStorageSpaceResponse)(nil), "cs3.storage.provider.v1beta1.CreateStorageSpaceResponse")
	proto.RegisterType((*ListStorageSpacesRequest)(nil), "cs3.storage.provider.v1beta1.ListStorageSpacesRequest")
	proto.RegisterType((*ListStorageSpacesRequest_Filter)(nil), "cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter")
	proto.RegisterType((*ListStorageSpacesResponse)(nil), "cs3.storage.provider.v1beta1.ListStorageSpacesResponse")
	proto.RegisterType((*UpdateStorageSpaceRequest)(nil), "cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest")
	proto.RegisterType((*UpdateStorageSpaceResponse)(nil), "cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse")
	proto.RegisterType((*DeleteStorageSpaceRequest)(nil), "cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest")
	proto.RegisterType((*DeleteStorageSpaceResponse)(nil), "cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse")
}

func init() {
	proto.RegisterFile("cs3/storage/provider/v1beta1/spaces_api.proto", fileDescriptor_a299dd75d83fb33e)
}

var fileDescriptor_a299dd75d83fb33e = []byte{
	// 897 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xcf, 0xd9, 0x67, 0x17, 0x4f, 0x9a, 0xe4, 0x58, 0x90, 0x38, 0x1f, 0xad, 0x6a, 0x8c, 0x84,
	0x02, 0x2a, 0x7b, 0xb2, 0x2d, 0x08, 0x95, 0x00, 0xc9, 0x76, 0x5c, 0xd9, 0x52, 0x89, 0xaf, 0x67,
	0x27, 0x15, 0x28, 0x92, 0x75, 0xb1, 0xd7, 0xe1, 0x14, 0xdb, 0x77, 0xb9, 0xdd, 0x2b, 0xa4, 0x4f,
	0x3c, 0x20, 0xf1, 0x00, 0xdf, 0x01, 0x89, 0x47, 0x9e, 0xf8, 0x1c, 0x7d, 0xe3, 0x5b, 0x20, 0x3e,
	0x02, 0x4f, 0x68, 0xff, 0x9c, 0xeb, 0xe2, 0x7f, 0x4d, 0x52, 0x45, 0xe2, 0x6d, 0x67, 0xe6, 0x37,
	0xb3, 0x33, 0xb3, 0xbf, 0x99, 0x3b, 0xf8, 0xb8, 0x4f, 0x2b, 0x36, 0x65, 0x41, 0xe4, 0x9d, 0x12,
	0x3b, 0x8c, 0x82, 0xa7, 0xfe, 0x80, 0x44, 0xf6, 0xd3, 0xd2, 0x09, 0x61, 0x5e, 0xc9, 0xa6, 0xa1,
	0xd7, 0x27, 0xb4, 0xe7, 0x85, 0x3e, 0x0e, 0xa3, 0x80, 0x05, 0xe8, 0x4e, 0x9f, 0x56, 0xb0, 0x82,
	0xe3, 0x04, 0x8e, 0x15, 0xdc, 0xfa, 0x90, 0x07, 0xf3, 0x07, 0x64, 0xc2, 0x7c, 0x76, 0x61, 0xc7,
	0x74, 0x26, 0x52, 0x44, 0x68, 0x10, 0x47, 0x7d, 0x42, 0x65, 0x20, 0x8b, 0x07, 0xb2, 0xa3, 0xb0,
	0xff, 0xe2, 0x2a, 0xe6, 0xb1, 0x38, 0xb1, 0xde, 0x5f, 0x99, 0xd5, 0x7f, 0x63, 0xdd, 0xe5, 0x68,
	0x76, 0x11, 0x12, 0x3a, 0x85, 0x08, 0x49, 0x99, 0x0b, 0xa7, 0x41, 0x70, 0x3a, 0x12, 0x71, 0x58,
	0x70, 0x12, 0x0f, 0xed, 0xa1, 0x4f, 0x46, 0x83, 0xde, 0xd8, 0xa3, 0x67, 0x12, 0x51, 0xfc, 0x4b,
	0x83, 0x7c, 0x3d, 0x22, 0x1e, 0x23, 0x1d, 0x79, 0x67, 0x87, 0xd7, 0xed, 0x92, 0xf3, 0x98, 0x50,
	0x86, 0x4a, 0x90, 0x0d, 0x42, 0xef, 0x3c, 0x26, 0xa6, 0x56, 0xd0, 0x76, 0x37, 0xcb, 0x79, 0xcc,
	0x9b, 0x20, 0x6f, 0x50, 0xf7, 0xe1, 0xb6, 0x00, 0xb8, 0x0a, 0x88, 0x3e, 0x81, 0x4c, 0xf0, 0xdd,
	0x84, 0x44, 0x66, 0x4a, 0x78, 0xdc, 0x13, 0x1e, 0x49, 0x63, 0x30, 0x6f, 0xcc, 0xd4, 0xf3, 0x90,
	0x92, 0xc8, 0x95, 0x68, 0x84, 0x40, 0xe7, 0x61, 0xcd, 0x74, 0x41, 0xdb, 0xcd, 0xb9, 0xe2, 0xcc,
	0x75, 0x13, 0x6f, 0x4c, 0x4c, 0x5d, 0xea, 0xf8, 0x19, 0x3d, 0x80, 0xcc, 0x79, 0x1c, 0x30, 0xcf,
	0xcc, 0x88, 0xf0, 0xef, 0xe3, 0x55, 0xaf, 0x82, 0x1f, 0x73, 0xa8, 0x2b, 0x3d, 0x8a, 0x7f, 0x6a,
	0x60, 0x2d, 0x2a, 0x95, 0x86, 0xc1, 0x84, 0x92, 0xab, 0xd4, 0x6a, 0x43, 0x56, 0xbe, 0x9d, 0x2a,
	0xf6, 0x1d, 0xe1, 0x12, 0x85, 0xfd, 0xa9, 0x43, 0x47, 0x98, 0x5d, 0x05, 0x43, 0x6d, 0xd8, 0x52,
	0xb9, 0xf6, 0x04, 0xbf, 0x44, 0xb9, 0x9b, 0xe5, 0x8f, 0x56, 0x57, 0xf1, 0x52, 0xba, 0xb7, 0xe9,
	0x8c, 0x54, 0xfc, 0x3b, 0x03, 0xe6, 0x23, 0x9f, 0xb2, 0x59, 0x08, 0xbd, 0xc6, 0xeb, 0x3d, 0x81,
	0x5b, 0x43, 0x7f, 0xc4, 0x48, 0xc4, 0x4b, 0x4a, 0xef, 0x6e, 0x96, 0xbf, 0x58, 0x9d, 0xda, 0xb2,
	0xbb, 0xf1, 0x43, 0x11, 0xc5, 0x4d, 0xa2, 0xa1, 0x07, 0x00, 0x2f, 0xb8, 0xa7, 0xca, 0xb6, 0xb0,
	0xa4, 0x27, 0x4e, 0xe8, 0x89, 0x1f, 0x72, 0xc8, 0x57, 0x1e, 0x3d, 0x73, 0x73, 0xc3, 0xe4, 0x88,
	0xde, 0x85, 0x5c, 0x28, 0x3a, 0xe6, 0x3f, 0x93, 0x5c, 0xc8, 0xb8, 0x6f, 0x70, 0x45, 0xc7, 0x7f,
	0x46, 0xd0, 0x5d, 0x00, 0x61, 0x64, 0xc1, 0x19, 0x99, 0x08, 0x52, 0xe4, 0x5c, 0x01, 0xef, 0x72,
	0x85, 0xf5, 0x3c, 0x0d, 0x59, 0x99, 0x0a, 0x3a, 0x52, 0x0c, 0xe3, 0xbd, 0xd8, 0x2e, 0xd7, 0xae,
	0x55, 0x17, 0xee, 0x5e, 0x84, 0x44, 0xb1, 0xf4, 0x4b, 0x48, 0xf9, 0x03, 0x45, 0x80, 0xfb, 0xaf,
	0xfe, 0x90, 0xad, 0x41, 0x73, 0xc3, 0x4d, 0xf9, 0x03, 0xce, 0x68, 0x39, 0x30, 0xb2, 0x29, 0xef,
	0xad, 0x19, 0x18, 0xe1, 0xa7, 0x86, 0xe6, 0x1e, 0x80, 0xa0, 0x51, 0x4f, 0x14, 0x26, 0xc6, 0xa4,
	0xb9, 0xe1, 0xe6, 0x84, 0x8e, 0x67, 0x88, 0xde, 0x06, 0x3d, 0xf4, 0xd8, 0xb7, 0xb2, 0x2f, 0xcd,
	0x0d, 0x57, 0x48, 0x68, 0x0f, 0x74, 0x1e, 0xd6, 0xcc, 0xbe, 0xfa, 0x85, 0xc2, 0xa1, 0x18, 0x83,
	0x2e, 0xc2, 0x1a, 0x70, 0xbb, 0xfb, 0xb5, 0xd3, 0xe8, 0xb5, 0x0e, 0x8e, 0xaa, 0x8f, 0x5a, 0xfb,
	0xc6, 0x06, 0xda, 0x84, 0x5b, 0x42, 0x73, 0xd0, 0x36, 0xb4, 0xa9, 0xd0, 0xda, 0x37, 0x52, 0x68,
	0x1b, 0x40, 0x08, 0xed, 0x27, 0x07, 0x0d, 0xd7, 0x48, 0xa3, 0xb7, 0x60, 0x47, 0xc8, 0x1d, 0xa7,
	0x5a, 0x6f, 0xf4, 0xf8, 0xd1, 0xd0, 0xd1, 0x16, 0xe4, 0x84, 0xd2, 0xa9, 0x76, 0x9b, 0x46, 0x66,
	0x2a, 0x1e, 0x76, 0x1a, 0xae, 0x91, 0xad, 0x65, 0x41, 0x67, 0x24, 0x1a, 0x17, 0xff, 0xd1, 0x20,
	0xbf, 0xe0, 0x61, 0x6e, 0x70, 0x7e, 0x1f, 0xc3, 0xf6, 0x4b, 0xf3, 0x4b, 0xcd, 0xb4, 0x98, 0x92,
	0xcb, 0x0c, 0xf0, 0xd6, 0xec, 0x00, 0x53, 0xf4, 0x01, 0xec, 0x4c, 0xc8, 0xf7, 0xac, 0x37, 0xc3,
	0x62, 0xb9, 0xef, 0xb6, 0xb8, 0xda, 0x49, 0x98, 0x5c, 0xfc, 0x55, 0x83, 0xfc, 0x61, 0x38, 0x78,
	0x7d, 0x8b, 0x7a, 0x6e, 0x17, 0xa5, 0xae, 0xb9, 0x8b, 0xf8, 0x7e, 0x5d, 0x94, 0xe1, 0xff, 0x79,
	0xbf, 0xfe, 0xa2, 0x41, 0x7e, 0x9f, 0x8c, 0xc8, 0x6b, 0xeb, 0xfa, 0xe7, 0x57, 0xdd, 0x16, 0x7c,
	0x57, 0x14, 0x7f, 0xd0, 0xc0, 0x5a, 0x94, 0xce, 0xcd, 0xb5, 0xb8, 0xfc, 0x87, 0x0e, 0x39, 0x49,
	0xdd, 0xaa, 0xd3, 0x42, 0x3f, 0x69, 0x80, 0xe6, 0xbf, 0xa9, 0x68, 0x6f, 0x75, 0x65, 0x4b, 0x7f,
	0x38, 0xac, 0xcf, 0x2e, 0xef, 0xa8, 0x6a, 0xff, 0x51, 0x83, 0x37, 0xe7, 0x96, 0x03, 0xfa, 0xf4,
	0x6a, 0x6b, 0xde, 0xda, 0xbb, 0xb4, 0x9f, 0x4a, 0x83, 0x37, 0x64, 0x7e, 0x08, 0xd6, 0x35, 0x64,
	0xe9, 0x60, 0xaf, 0x6b, 0xc8, 0x8a, 0x79, 0xe3, 0x99, 0xcc, 0x73, 0x65, 0x5d, 0x26, 0x4b, 0xc9,
	0xbe, 0x2e, 0x93, 0xe5, 0xb4, 0xac, 0xfd, 0xac, 0x41, 0xa1, 0x1f, 0x8c, 0x57, 0xfa, 0xd7, 0x0c,
	0x47, 0x69, 0xaa, 0xa1, 0xef, 0xf0, 0xff, 0x01, 0x47, 0xfb, 0x66, 0x27, 0x41, 0x29, 0xd0, 0x6f,
	0xa9, 0x74, 0xbd, 0xe3, 0xfc, 0x9e, 0xba, 0x53, 0xa7, 0x95, 0x64, 0x3c, 0x70, 0xe2, 0x87, 0x8f,
	0x4a, 0x35, 0x0e, 0x7a, 0x2e, 0xcc, 0xc7, 0xca, 0x7c, 0x9c, 0x98, 0x8f, 0x95, 0xf9, 0x24, 0x2b,
	0xfe, 0x36, 0x2a, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xea, 0x78, 0xcc, 0x07, 0xff, 0x0b, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpacesAPIClient is the client API for SpacesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpacesAPIClient interface {
	// Creates a storage space.
	CreateStorageSpace(ctx context.Context, in *CreateStorageSpaceRequest, opts ...grpc.CallOption) (*CreateStorageSpaceResponse, error)
	// Lists storage spaces.
	ListStorageSpaces(ctx context.Context, in *ListStorageSpacesRequest, opts ...grpc.CallOption) (*ListStorageSpacesResponse, error)
	// Updates a storage space.
	UpdateStorageSpace(ctx context.Context, in *UpdateStorageSpaceRequest, opts ...grpc.CallOption) (*UpdateStorageSpaceResponse, error)
	// Deletes a storage space.
	DeleteStorageSpace(ctx context.Context, in *DeleteStorageSpaceRequest, opts ...grpc.CallOption) (*DeleteStorageSpaceResponse, error)
}

type spacesAPIClient struct {
	cc *grpc.ClientConn
}

func NewSpacesAPIClient(cc *grpc.ClientConn) SpacesAPIClient {
	return &spacesAPIClient{cc}
}

func (c *spacesAPIClient) CreateStorageSpace(ctx context.Context, in *CreateStorageSpaceRequest, opts ...grpc.CallOption) (*CreateStorageSpaceResponse, error) {
	out := new(CreateStorageSpaceResponse)
	err := c.cc.Invoke(ctx, "/cs3.storage.provider.v1beta1.SpacesAPI/CreateStorageSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacesAPIClient) ListStorageSpaces(ctx context.Context, in *ListStorageSpacesRequest, opts ...grpc.CallOption) (*ListStorageSpacesResponse, error) {
	out := new(ListStorageSpacesResponse)
	err := c.cc.Invoke(ctx, "/cs3.storage.provider.v1beta1.SpacesAPI/ListStorageSpaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacesAPIClient) UpdateStorageSpace(ctx context.Context, in *UpdateStorageSpaceRequest, opts ...grpc.CallOption) (*UpdateStorageSpaceResponse, error) {
	out := new(UpdateStorageSpaceResponse)
	err := c.cc.Invoke(ctx, "/cs3.storage.provider.v1beta1.SpacesAPI/UpdateStorageSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacesAPIClient) DeleteStorageSpace(ctx context.Context, in *DeleteStorageSpaceRequest, opts ...grpc.CallOption) (*DeleteStorageSpaceResponse, error) {
	out := new(DeleteStorageSpaceResponse)
	err := c.cc.Invoke(ctx, "/cs3.storage.provider.v1beta1.SpacesAPI/DeleteStorageSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpacesAPIServer is the server API for SpacesAPI service.
type SpacesAPIServer interface {
	// Creates a storage space.
	CreateStorageSpace(context.Context, *CreateStorageSpaceRequest) (*CreateStorageSpaceResponse, error)
	// Lists storage spaces.
	ListStorageSpaces(context.Context, *ListStorageSpacesRequest) (*ListStorageSpacesResponse, error)
	// Updates a storage space.
	UpdateStorageSpace(context.Context, *UpdateStorageSpaceRequest) (*UpdateStorageSpaceResponse, error)
	// Deletes a storage space.
	DeleteStorageSpace(context.Context, *DeleteStorageSpaceRequest) (*DeleteStorageSpaceResponse, error)
}

// UnimplementedSpacesAPIServer can be embedded to have forward compatible implementations.
type UnimplementedSpacesAPIServer struct {
}

func (*UnimplementedSpacesAPIServer) CreateStorageSpace(ctx context.Context, req *CreateStorageSpaceRequest) (*CreateStorageSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStorageSpace not implemented")
}
func (*UnimplementedSpacesAPIServer) ListStorageSpaces(ctx context.Context, req *ListStorageSpacesRequest) (*ListStorageSpacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStorageSpaces not implemented")
}
func (*UnimplementedSpacesAPIServer) UpdateStorageSpace(ctx context.Context, req *UpdateStorageSpaceRequest) (*UpdateStorageSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStorageSpace not implemented")
}
func (*UnimplementedSpacesAPIServer) DeleteStorageSpace(ctx context.Context, req *DeleteStorageSpaceRequest) (*DeleteStorageSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStorageSpace not implemented")
}

func RegisterSpacesAPIServer(s *grpc.Server, srv SpacesAPIServer) {
	s.RegisterService(&_SpacesAPI_serviceDesc, srv)
}

func _SpacesAPI_CreateStorageSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStorageSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacesAPIServer).CreateStorageSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.storage.provider.v1beta1.SpacesAPI/CreateStorageSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacesAPIServer).CreateStorageSpace(ctx, req.(*CreateStorageSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpacesAPI_ListStorageSpaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStorageSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacesAPIServer).ListStorageSpaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.storage.provider.v1beta1.SpacesAPI/ListStorageSpaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacesAPIServer).ListStorageSpaces(ctx, req.(*ListStorageSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpacesAPI_UpdateStorageSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStorageSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacesAPIServer).UpdateStorageSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.storage.provider.v1beta1.SpacesAPI/UpdateStorageSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacesAPIServer).UpdateStorageSpace(ctx, req.(*UpdateStorageSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpacesAPI_DeleteStorageSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorageSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacesAPIServer).DeleteStorageSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.storage.provider.v1beta1.SpacesAPI/DeleteStorageSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacesAPIServer).DeleteStorageSpace(ctx, req.(*DeleteStorageSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpacesAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cs3.storage.provider.v1beta1.SpacesAPI",
	HandlerType: (*SpacesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStorageSpace",
			Handler:    _SpacesAPI_CreateStorageSpace_Handler,
		},
		{
			MethodName: "ListStorageSpaces",
			Handler:    _SpacesAPI_ListStorageSpaces_Handler,
		},
		{
			MethodName: "UpdateStorageSpace",
			Handler:    _SpacesAPI_UpdateStorageSpace_Handler,
		},
		{
			MethodName: "DeleteStorageSpace",
			Handler:    _SpacesAPI_DeleteStorageSpace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cs3/storage/provider/v1beta1/spaces_api.proto",
}
